#:schema https://json.schemastore.org/any.json
# Config file for [Air](https://github.com/air-verse/air) in TOML format

root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./bin/server ./cmd/server/main.go"
  bin = "./bin/server"
  full_bin = "./bin/server"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "web", "docs", "bin"]
  include_dir = []
  exclude_file = []
  delay = 1000 # ms
  stop_on_error = true
  log = "air.log"

[log]
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
